name: Jekyll Build

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install Bundler
        run: gem install bundler --no-document
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Build site with Jekyll
        run: bundle exec jekyll build --verbose
      - name: Upload generated site
        uses: actions/upload-artifact@v4
        with:
          name: site-artifact
          path: _site
name: Jekyll Build

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Build site
        run: bundle exec jekyll build --verbose
      - name: Run html-proofer (optional)
        if: always()
        run: |
          if bundle list | grep html-proofer; then
            bundle exec htmlproofer ./_site --assume-extension
          else
            echo "html-proofer not installed; skipping"
          fi